def mainfun(_):
    return error